### ISSUE TITLE
Url  upload throwing js errors

### ISSUE THREAD

**Issue by Raidm404** [prasathmani/tinyfilemanager#1110]
Hi,
 The url upload is not working  Showing the following error on browser console

```
Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.success (index.php?p=fun&upload:418:33)
    at c (jquery-3.6.1.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.1.min.js:2:29072)
    at l (jquery-3.6.1.min.js:2:80045)
    at XMLHttpRequest.<anonymous> (jquery-3.6.1.min.js:2:82499)
```

**Comment by Raidm404** [comment]
Hello,
Not the url is valid . I also tried with image URL . It is not working

**Comment by Raidm404** [comment]
Hi,
 Never mind I fixed. it was my issues . Thanks for the help
